In [ ]:
from google.colab import files
uploaded=files.upload()

Saving RTA Dataset.csv to RTA Dataset.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("RTA Dataset.csv")

In [ ]:
df

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [ ]:
df.head(30)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
5,14:15:00,Friday,31-50,Male,NaN,Unknown,NaN,NaN,NaN,NaN,...,U-Turn,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Slight Injury
6,17:30:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,NaN,...,Moving Backward,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,Other,Slight Injury
7,17:20:00,Friday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Governmental,Above 10yr,...,U-Turn,na,na,na,na,NaN,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
8,17:20:00,Friday,18-30,Male,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from driver's nearside,Changing lane to the right,Slight Injury
9,17:20:00,Friday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,2-5yrs,...,U-Turn,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,Owner,1-2yr,Public (13?45 seats),Owner,Unknown,...,Turnover,na,na,na,na,NaN,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,Employee,No Licence,Automobile,Owner,NaN,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Public (> 45 seats),Owner,2-5yrs,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Waiting to go,na,na,na,na,Other,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Automobile,Owner,1-2yr,...,Going straight,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury
15,22:45:00,Monday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,Owner,5-10yr,Public (13?45 seats),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,Employee,2-5yr,Public (13?45 seats),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,Above 10yr,...,Moving Backward,na,na,na,na,Unemployed,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
19,08:20:00,Tuesday,18-30,Male,Junior high school,Employee,Below 1yr,Long lorry,Owner,5-10yrs,...,Going straight,Driver or rider,Male,Under 18,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
20,08:20:00,Tuesday,Under 18,Male,Junior high school,Employee,2-5yr,Lorry (41?100Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
21,15:10:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,Lorry (11?40Q),Owner,5-10yrs,...,Moving Backward,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Serious Injury
22,12:11:00,Thursday,18-30,Male,Elementary school,Employee,5-10yr,Lorry (41?100Q),Owner,NaN,...,Getting off,Passenger,Female,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Serious Injury
23,12:11:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Public (12 seats),Owner,NaN,...,Reversing,Passenger,Male,18-30,3,Employee,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
24,18:36:00,Wednesday,18-30,Male,NaN,Unknown,NaN,NaN,NaN,NaN,...,Turnover,na,na,na,na,Driver,Normal,Not a Pedestrian,Improper parking,Slight Injury
25,18:36:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Taxi,Owner,Above 10yr,...,Going straight,Driver or rider,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Other,Slight Injury
26,18:36:00,Wednesday,18-30,Unknown,Junior high school,Employee,5-10yr,NaN,Owner,2-5yrs,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the left,Slight Injury
27,14:35:00,Friday,18-30,Male,Above high school,Employee,2-5yr,Automobile,Owner,2-5yrs,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
28,12:25:00,Tuesday,Over 51,Unknown,NaN,Unknown,NaN,NaN,NaN,NaN,...,Going straight,Driver or rider,Male,31-50,3,NaN,NaN,Not a Pedestrian,No priority to pedestrian,Slight Injury
29,12:25:00,Tuesday,18-30,Male,NaN,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,18-30,2,Driver,Normal,Not a Pedestrian,Overspeed,Slight Injury

In [ ]:
df.tail(5)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [ ]:
df.shape

(12316, 32)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

In [ ]:
df['Educational_level'] = df['Educational_level'].fillna('Unknown')
df['Vehicle_driver_relation'] = df['Vehicle_driver_relation'].fillna('Unknown')
df['Driving_experience'] = df['Driving_experience'].fillna('Unknown')
df['Type_of_vehicle'] = df['Type_of_vehicle'].fillna('Unknown')
df['Service_year_of_vehicle'] = df['Service_year_of_vehicle'].fillna('Unknown')
df['Area_accident_occured'] = df['Area_accident_occured'].fillna('Unknown')
df['Lanes_or_Medians'] = df['Lanes_or_Medians'].fillna('Unknown')
df['Road_allignment'] = df['Road_allignment'].fillna('Unknown')
df['Types_of_Junction'] = df['Types_of_Junction'].fillna('Unknown')
df['Road_surface_type'] = df['Road_surface_type'].fillna('Unknown')
df['Vehicle_movement'] = df['Vehicle_movement'].fillna('Unknown')
df['Work_of_casuality'] = df['Work_of_casuality'].fillna('Unknown')

In [ ]:
df['Owner_of_vehicle'] = df['Owner_of_vehicle'].fillna(
    df['Owner_of_vehicle'].mode()[0]
)

df['Fitness_of_casuality'] = df['Fitness_of_casuality'].fillna(
    df['Fitness_of_casuality'].mode()[0]
)

In [ ]:
df.head(30)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,Unknown,Normal,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,Unknown,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,5-10yrs,...,Going straight,na,na,na,na,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
5,14:15:00,Friday,31-50,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,U-Turn,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Slight Injury
6,17:30:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,Unknown,...,Moving Backward,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,Other,Slight Injury
7,17:20:00,Friday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Governmental,Above 10yr,...,U-Turn,na,na,na,na,Unknown,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
8,17:20:00,Friday,18-30,Male,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from driver's nearside,Changing lane to the right,Slight Injury
9,17:20:00,Friday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,2-5yrs,...,U-Turn,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,Owner,1-2yr,Public (13?45 seats),Owner,Unknown,...,Turnover,na,na,na,na,Unknown,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,Employee,No Licence,Automobile,Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Public (> 45 seats),Owner,2-5yrs,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Waiting to go,na,na,na,na,Other,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Automobile,Owner,1-2yr,...,Going straight,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury
15,22:45:00,Monday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (11?40Q),Owner,Unknown,...,Going straight,na,na,na,na,Unknown,Normal,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,Owner,5-10yr,Public (13?45 seats),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,Employee,2-5yr,Public (13?45 seats),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,Above 10yr,...,Moving Backward,na,na,na,na,Unemployed,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
19,08:20:00,Tuesday,18-30,Male,Junior high school,Employee,Below 1yr,Long lorry,Owner,5-10yrs,...,Going straight,Driver or rider,Male,Under 18,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
20,08:20:00,Tuesday,Under 18,Male,Junior high school,Employee,2-5yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
21,15:10:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,Lorry (11?40Q),Owner,5-10yrs,...,Moving Backward,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Serious Injury
22,12:11:00,Thursday,18-30,Male,Elementary school,Employee,5-10yr,Lorry (41?100Q),Owner,Unknown,...,Getting off,Passenger,Female,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Serious Injury
23,12:11:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Public (12 seats),Owner,Unknown,...,Reversing,Passenger,Male,18-30,3,Employee,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
24,18:36:00,Wednesday,18-30,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Turnover,na,na,na,na,Driver,Normal,Not a Pedestrian,Improper parking,Slight Injury
25,18:36:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Taxi,Owner,Above 10yr,...,Going straight,Driver or rider,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Other,Slight Injury
26,18:36:00,Wednesday,18-30,Unknown,Junior high school,Employee,5-10yr,Unknown,Owner,2-5yrs,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the left,Slight Injury
27,14:35:00,Friday,18-30,Male,Above high school,Employee,2-5yr,Automobile,Owner,2-5yrs,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
28,12:25:00,Tuesday,Over 51,Unknown,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Unknown,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
29,12:25:00,Tuesday,18-30,Male,Unknown,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,2,Driver,Normal,Not a Pedestrian,Overspeed,Slight Injury

In [ ]:
df['Casualty_severity'].unique()

array(['na', '3', '2', '1'], dtype=object)

In [ ]:
df['Casualty_severity'] = df['Casualty_severity'].replace('na', np.nan)

In [ ]:
df['Casualty_severity'] = df['Casualty_severity'].fillna(
    df['Casualty_severity'].mode()[0]
)

In [ ]:
df.head(30)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,3,Unknown,Normal,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,3,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,Unknown,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,5-10yrs,...,Going straight,na,na,na,3,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
5,14:15:00,Friday,31-50,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,U-Turn,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Slight Injury
6,17:30:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,Unknown,...,Moving Backward,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,Other,Slight Injury
7,17:20:00,Friday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Governmental,Above 10yr,...,U-Turn,na,na,na,3,Unknown,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
8,17:20:00,Friday,18-30,Male,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from driver's nearside,Changing lane to the right,Slight Injury
9,17:20:00,Friday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,2-5yrs,...,U-Turn,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,Owner,1-2yr,Public (13?45 seats),Owner,Unknown,...,Turnover,na,na,na,3,Unknown,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,Employee,No Licence,Automobile,Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Public (> 45 seats),Owner,2-5yrs,...,Going straight,na,na,na,3,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Waiting to go,na,na,na,3,Other,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Automobile,Owner,1-2yr,...,Going straight,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury
15,22:45:00,Monday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (11?40Q),Owner,Unknown,...,Going straight,na,na,na,3,Unknown,Normal,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,Owner,5-10yr,Public (13?45 seats),Owner,Unknown,...,Going straight,na,na,na,3,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,Employee,2-5yr,Public (13?45 seats),Owner,Unknown,...,Going straight,na,na,na,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,Above 10yr,...,Moving Backward,na,na,na,3,Unemployed,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
19,08:20:00,Tuesday,18-30,Male,Junior high school,Employee,Below 1yr,Long lorry,Owner,5-10yrs,...,Going straight,Driver or rider,Male,Under 18,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
20,08:20:00,Tuesday,Under 18,Male,Junior high school,Employee,2-5yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,na,na,na,3,Driver,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
21,15:10:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,Lorry (11?40Q),Owner,5-10yrs,...,Moving Backward,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Serious Injury
22,12:11:00,Thursday,18-30,Male,Elementary school,Employee,5-10yr,Lorry (41?100Q),Owner,Unknown,...,Getting off,Passenger,Female,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Serious Injury
23,12:11:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Public (12 seats),Owner,Unknown,...,Reversing,Passenger,Male,18-30,3,Employee,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
24,18:36:00,Wednesday,18-30,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Turnover,na,na,na,3,Driver,Normal,Not a Pedestrian,Improper parking,Slight Injury
25,18:36:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Taxi,Owner,Above 10yr,...,Going straight,Driver or rider,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Other,Slight Injury
26,18:36:00,Wednesday,18-30,Unknown,Junior high school,Employee,5-10yr,Unknown,Owner,2-5yrs,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the left,Slight Injury
27,14:35:00,Friday,18-30,Male,Above high school,Employee,2-5yr,Automobile,Owner,2-5yrs,...,Going straight,na,na,na,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
28,12:25:00,Tuesday,Over 51,Unknown,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Unknown,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
29,12:25:00,Tuesday,18-30,Male,Unknown,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,2,Driver,Normal,Not a Pedestrian,Overspeed,Slight Injury

In [ ]:
df['Sex_of_casualty'] = df['Sex_of_casualty'].replace('na', 'Unknown')
df['Age_band_of_casualty'] = df['Age_band_of_casualty'].replace('na', 'Unknown')
df['Casualty_class'] = df['Casualty_class'].replace('na', 'Unknown')

In [ ]:
df.head(30)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,Unknown,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,5-10yrs,...,Going straight,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,Overtaking,Slight Injury
5,14:15:00,Friday,31-50,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,U-Turn,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Slight Injury
6,17:30:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,Unknown,...,Moving Backward,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,Other,Slight Injury
7,17:20:00,Friday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Governmental,Above 10yr,...,U-Turn,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
8,17:20:00,Friday,18-30,Male,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from driver's nearside,Changing lane to the right,Slight Injury
9,17:20:00,Friday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,2-5yrs,...,U-Turn,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,Owner,1-2yr,Public (13?45 seats),Owner,Unknown,...,Turnover,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,Employee,No Licence,Automobile,Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Public (> 45 seats),Owner,2-5yrs,...,Going straight,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Waiting to go,Unknown,Unknown,Unknown,3,Other,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Automobile,Owner,1-2yr,...,Going straight,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury
15,22:45:00,Monday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (11?40Q),Owner,Unknown,...,Going straight,Unknown,Unknown,Unknown,3,Unknown,Normal,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,Owner,5-10yr,Public (13?45 seats),Owner,Unknown,...,Going straight,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,Employee,2-5yr,Public (13?45 seats),Owner,Unknown,...,Going straight,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,Unknown,Owner,Above 10yr,...,Moving Backward,Unknown,Unknown,Unknown,3,Unemployed,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
19,08:20:00,Tuesday,18-30,Male,Junior high school,Employee,Below 1yr,Long lorry,Owner,5-10yrs,...,Going straight,Driver or rider,Male,Under 18,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
20,08:20:00,Tuesday,Under 18,Male,Junior high school,Employee,2-5yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
21,15:10:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,Lorry (11?40Q),Owner,5-10yrs,...,Moving Backward,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Serious Injury
22,12:11:00,Thursday,18-30,Male,Elementary school,Employee,5-10yr,Lorry (41?100Q),Owner,Unknown,...,Getting off,Passenger,Female,31-50,3,Driver,Normal,Not a Pedestrian,Overloading,Serious Injury
23,12:11:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Public (12 seats),Owner,Unknown,...,Reversing,Passenger,Male,18-30,3,Employee,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
24,18:36:00,Wednesday,18-30,Male,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Turnover,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,Improper parking,Slight Injury
25,18:36:00,Wednesday,18-30,Male,Junior high school,Employee,2-5yr,Taxi,Owner,Above 10yr,...,Going straight,Driver or rider,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Other,Slight Injury
26,18:36:00,Wednesday,18-30,Unknown,Junior high school,Employee,5-10yr,Unknown,Owner,2-5yrs,...,Going straight,Pedestrian,Male,Under 18,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the left,Slight Injury
27,14:35:00,Friday,18-30,Male,Above high school,Employee,2-5yr,Automobile,Owner,2-5yrs,...,Going straight,Unknown,Unknown,Unknown,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
28,12:25:00,Tuesday,Over 51,Unknown,Unknown,Unknown,Unknown,Unknown,Owner,Unknown,...,Going straight,Driver or rider,Male,31-50,3,Unknown,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
29,12:25:00,Tuesday,18-30,Male,Unknown,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,2,Driver,Normal,Not a Pedestrian,Overspeed,Slight Injury